"use strict";

const fs = require("fs/promises");
const path = require("path");
const matter = require("gray-matter");

const DEFAULT_RULES_DIR = ".cursor/rules";
const OUT_SCOPED_DIR = ".claude/rules";
const OUT_ALWAYS = "CLAUDE.md";

const BANNER = `<!-- Generated by cursor-rules-to-claude — re-run after changing Cursor rules. -->\n\n`;

const ALWAYS_BEGIN = "<!-- cursor-rules-to-claude:always-begin -->";
const ALWAYS_END = "<!-- cursor-rules-to-claude:always-end -->";

/**
 * @param {string} dir
 * @returns {Promise<string[]>}
 */
async function walkFiles(dir) {
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch (e) {
    if (e && e.code === "ENOENT") return [];
    throw e;
  }
  const out = [];
  for (const ent of entries) {
    const full = path.join(dir, ent.name);
    if (ent.isDirectory()) {
      out.push(...(await walkFiles(full)));
    } else if (ent.isFile()) {
      out.push(full);
    }
  }
  return out;
}

/**
 * @param {unknown} v
 * @returns {string[]}
 */
function normalizeGlobs(v) {
  if (v == null) return [];
  if (Array.isArray(v)) {
    return v.map(String).map((s) => s.trim()).filter(Boolean);
  }
  const s = String(v).trim();
  if (!s) return [];
  return [s];
}

/**
 * @param {unknown} v
 * @returns {boolean}
 */
function isAlwaysApply(v) {
  if (v === true) return true;
  if (v === false || v == null) return false;
  if (typeof v === "string") {
    const t = v.trim().toLowerCase();
    return t === "true" || t === "yes" || t === "1";
  }
  return Boolean(v);
}

/**
 * Stable slug from rules-relative path for filenames.
 * @param {string} rel - posix-style relative path without leading ./
 */
function slugFromRel(rel) {
  const noExt = rel.replace(/\.(mdc|md)$/i, "");
  return noExt.replace(/\\/g, "/").replace(/\//g, "-");
}

/**
 * @param {object} opts
 * @param {string} opts.root - workspace root
 * @param {string} [opts.rulesDir]
 * @param {boolean} [opts.dryRun]
 * @param {boolean} [opts.noBanner]
 */
async function convert(opts) {
  const root = path.resolve(opts.root);
  const rulesDir = path.join(root, opts.rulesDir || DEFAULT_RULES_DIR);
  const dryRun = Boolean(opts.dryRun);
  const noBanner = Boolean(opts.noBanner);

  const allFiles = await walkFiles(rulesDir);
  const ruleFiles = allFiles
    .filter((f) => /\.(mdc|md)$/i.test(f))
    .sort((a, b) => a.localeCompare(b));

  if (ruleFiles.length === 0) {
    return {
      ok: true,
      message: `No rule files found under ${path.relative(root, rulesDir) || "."}`,
      alwaysParts: [],
      scopedWrites: [],
      dryRun,
    };
  }

  /** @type {{ source: string, body: string, description?: string }[]} */
  const alwaysParts = [];
  /** @type {{ dest: string, content: string }[]} */
  const scopedWrites = [];

  for (const abs of ruleFiles) {
    const raw = await fs.readFile(abs, "utf8");
    const parsed = matter(raw);
    const data = parsed.data || {};
    const rel = path.relative(rulesDir, abs).split(path.sep).join("/");
    const slug = slugFromRel(rel);
    const description =
      typeof data.description === "string" ? data.description.trim() : "";
    const globs = normalizeGlobs(data.globs);
    const always = isAlwaysApply(data.alwaysApply);

    const header = `<!-- Source: ${DEFAULT_RULES_DIR}/${rel} -->\n`;

    if (always) {
      let block = header;
      if (description) {
        block += `> ${description.replace(/\n/g, "\n> ")}\n\n`;
      }
      block += parsed.content.trim() ? `${parsed.content.trim()}\n\n` : "";
      alwaysParts.push({
        source: `${DEFAULT_RULES_DIR}/${rel}`,
        body: block,
        description,
      });
      continue;
    }

    const globHint =
      globs.length > 0
        ? `<!-- applyTo (from Cursor globs): ${globs.join(", ")} -->\n`
        : "";

    if (globs.length === 0) {
      const name = `${slug}.md`;
      const dest = path.join(root, OUT_SCOPED_DIR, name);
      const content =
        (noBanner ? "" : BANNER) +
        globHint +
        header +
        (parsed.content.trim() || "(empty rule body)") +
        "\n";
      scopedWrites.push({ dest, content });
      continue;
    }

    globs.forEach((g, i) => {
      const suffix = globs.length > 1 ? `-${i + 1}` : "";
      const name = `${slug}${suffix}.md`;
      const dest = path.join(root, OUT_SCOPED_DIR, name);
      const content =
        (noBanner ? "" : BANNER) +
        `<!-- applyTo: ${g} -->\n` +
        header +
        (parsed.content.trim() || "(empty rule body)") +
        "\n";
      scopedWrites.push({ dest, content });
    });
  }

  let alwaysBlock = "";
  if (alwaysParts.length > 0) {
    const inner =
      (noBanner ? "" : BANNER) +
      "# Project instructions (from Cursor rules)\n\n" +
      alwaysParts.map((p) => `## ${p.source}\n\n${p.body.trim()}\n`).join("\n");
    alwaysBlock = `${ALWAYS_BEGIN}\n${inner.trim()}\n${ALWAYS_END}\n`;
  }

  if (!dryRun) {
    const outScoped = path.join(root, OUT_SCOPED_DIR);
    await fs.mkdir(outScoped, { recursive: true });

    for (const { dest, content } of scopedWrites) {
      await fs.mkdir(path.dirname(dest), { recursive: true });
      await fs.writeFile(dest, content, "utf8");
    }

    const alwaysPath = path.join(root, OUT_ALWAYS);
    let prior = "";
    try {
      prior = await fs.readFile(alwaysPath, "utf8");
    } catch {
      /* new */
    }

    let next = prior;
    if (prior.includes(ALWAYS_BEGIN) && prior.includes(ALWAYS_END)) {
      const re = new RegExp(
        `${escapeRe(ALWAYS_BEGIN)}[\\s\\S]*?${escapeRe(ALWAYS_END)}\\n*`,
        "m"
      );
      next = prior.replace(re, "");
    }

    if (alwaysBlock) {
      const sep = next.trimEnd().length ? "\n\n" : "";
      next = `${next.trimEnd()}${sep}${alwaysBlock}`;
      await fs.writeFile(alwaysPath, next.endsWith("\n") ? next : `${next}\n`, "utf8");
    } else if (next.trim().length > 0) {
      await fs.writeFile(alwaysPath, next.endsWith("\n") ? next : `${next}\n`, "utf8");
    } else {
      try {
        await fs.unlink(alwaysPath);
      } catch (e) {
        if (e && e.code !== "ENOENT") throw e;
      }
    }
  }

  return {
    ok: true,
    message: `Processed ${ruleFiles.length} rule file(s).`,
    alwaysParts,
    scopedWrites,
    alwaysPath: alwaysBlock ? path.join(root, OUT_ALWAYS) : null,
    dryRun,
  };
}

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

module.exports = { convert, walkFiles, DEFAULT_RULES_DIR, OUT_ALWAYS, OUT_SCOPED_DIR };
