"use strict";

const fs = require("fs/promises");
const path = require("path");
const { pathToFileURL } = require("node:url");
const matter = require("gray-matter");

const DEFAULT_RULES_DIR = ".cursor/rules";
const OUT_SCOPED_DIR = ".claude/rules";
const OUT_ALWAYS = "CLAUDE.md";

const BANNER = `<!-- Generated by cursor-rules-to-claude — re-run after changing Cursor rules. -->\n\n`;

/**
 * Resolve candidate under workspace root or throw (mitigates path traversal via --cwd / --rules-dir).
 * @param {string} root
 * @param {string} candidate
 * @returns {string} canonical absolute path under root (or root itself)
 */
function resolvePathUnderRoot(root, candidate) {
  const r = path.resolve(root);
  const t = path.resolve(candidate);
  if (t === r) return t;
  const rel = path.relative(r, t);
  if (!rel || rel.startsWith("..") || path.isAbsolute(rel)) {
    throw new Error(`Refusing path outside workspace (${r}): ${candidate}`);
  }
  return t;
}

function assertPathInsideRoot(root, absoluteTarget) {
  resolvePathUnderRoot(root, absoluteTarget);
}

const ALWAYS_BEGIN = "<!-- cursor-rules-to-claude:always-begin -->";
const ALWAYS_END = "<!-- cursor-rules-to-claude:always-end -->";

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Merge generated scoped rule output into an existing file (per-slug block), never blind overwrite.
 * @param {string} existing
 * @param {string} slug - filename stem under .claude/rules
 * @param {string} generated
 */
function mergeScopedRuleFile(existing, slug, generated) {
  const begin = `<!-- cursor-rules-to-claude:scoped:${slug}:begin -->`;
  const end = `<!-- cursor-rules-to-claude:scoped:${slug}:end -->`;
  const block = `${begin}\n${generated.trim()}\n${end}\n`;
  const text = existing || "";
  if (!text.trim()) {
    return block;
  }
  if (text.includes(begin) && text.includes(end)) {
    const re = new RegExp(
      `${escapeRe(begin)}[\\s\\S]*?${escapeRe(end)}\\n*`,
      "m"
    );
    return text.replace(re, block);
  }
  return `${text.trimEnd()}\n\n---\n\n${block}`;
}

/**
 * @param {string} dir
 * @returns {Promise<string[]>}
 */
async function walkFiles(root, dir) {
  const safeDir = resolvePathUnderRoot(root, dir);
  let entries;
  try {
    entries = await fs.readdir(pathToFileURL(safeDir), { withFileTypes: true });
  } catch (e) {
    if (e && e.code === "ENOENT") return [];
    throw e;
  }
  const out = [];
  for (const ent of entries) {
    const full = path.join(safeDir, ent.name);
    const safeFull = resolvePathUnderRoot(root, full);
    if (ent.isDirectory()) {
      out.push(...(await walkFiles(root, safeFull)));
    } else if (ent.isFile()) {
      out.push(safeFull);
    }
  }
  return out;
}

/**
 * @param {unknown} v
 * @returns {string[]}
 */
function normalizeGlobs(v) {
  if (v == null) return [];
  if (Array.isArray(v)) {
    return v.map(String).map((s) => s.trim()).filter(Boolean);
  }
  const s = String(v).trim();
  if (!s) return [];
  return [s];
}

/**
 * @param {unknown} v
 * @returns {boolean}
 */
function isAlwaysApply(v) {
  if (v === true) return true;
  if (v === false || v == null) return false;
  if (typeof v === "string") {
    const t = v.trim().toLowerCase();
    return t === "true" || t === "yes" || t === "1";
  }
  return Boolean(v);
}

/**
 * Stable slug from rules-relative path for filenames.
 * @param {string} rel - posix-style relative path without leading ./
 */
function slugFromRel(rel) {
  const noExt = rel.replace(/\.(mdc|md)$/i, "");
  return noExt.replace(/\\/g, "/").replace(/\//g, "-");
}

/**
 * @param {object} opts
 * @param {string} opts.root - workspace root
 * @param {string} [opts.rulesDir]
 * @param {boolean} [opts.dryRun]
 * @param {boolean} [opts.noBanner]
 */
async function safeWriteFile(root, dest, content, encoding = "utf8") {
  const out = resolvePathUnderRoot(root, dest);
  const payload = Buffer.from(String(content), encoding);
  return fs.writeFile(pathToFileURL(out), payload);
}

async function convert(opts) {
  const root = path.resolve(opts.root);
  let rulesDir;
  if (!opts.rulesDir) {
    rulesDir = path.join(root, DEFAULT_RULES_DIR);
  } else if (path.isAbsolute(opts.rulesDir)) {
    rulesDir = path.resolve(opts.rulesDir);
  } else {
    rulesDir = path.resolve(path.join(root, opts.rulesDir));
  }
  assertPathInsideRoot(root, rulesDir);
  const dryRun = Boolean(opts.dryRun);
  const noBanner = Boolean(opts.noBanner);

  const allFiles = await walkFiles(root, rulesDir);
  const ruleFiles = allFiles
    .filter((f) => /\.(mdc|md)$/i.test(f))
    .sort((a, b) => a.localeCompare(b));

  if (ruleFiles.length === 0) {
    return {
      ok: true,
      message: `No rule files found under ${path.relative(root, rulesDir) || "."}`,
      alwaysParts: [],
      scopedWrites: [],
      dryRun,
    };
  }

  /** @type {{ source: string, body: string, description?: string }[]} */
  const alwaysParts = [];
  /** @type {{ dest: string, content: string }[]} */
  const scopedWrites = [];

  for (const abs of ruleFiles) {
    const raw = await fs.readFile(pathToFileURL(abs), "utf8");
    const parsed = matter(raw);
    const data = parsed.data || {};
    const rel = path.relative(rulesDir, abs).split(path.sep).join("/");
    const slug = slugFromRel(rel);
    const description =
      typeof data.description === "string" ? data.description.trim() : "";
    const globs = normalizeGlobs(data.globs);
    const always = isAlwaysApply(data.alwaysApply);

    const header = `<!-- Source: ${DEFAULT_RULES_DIR}/${rel} -->\n`;

    if (always) {
      let block = header;
      if (description) {
        block += `> ${description.replace(/\n/g, "\n> ")}\n\n`;
      }
      block += parsed.content.trim() ? `${parsed.content.trim()}\n\n` : "";
      alwaysParts.push({
        source: `${DEFAULT_RULES_DIR}/${rel}`,
        body: block,
        description,
      });
      continue;
    }

    const globHint =
      globs.length > 0
        ? `<!-- applyTo (from Cursor globs): ${globs.join(", ")} -->\n`
        : "";

    if (globs.length === 0) {
      const name = `${slug}.md`;
      const dest = path.join(root, OUT_SCOPED_DIR, name);
      const content =
        (noBanner ? "" : BANNER) +
        globHint +
        header +
        (parsed.content.trim() || "(empty rule body)") +
        "\n";
      scopedWrites.push({ dest, content });
      continue;
    }

    globs.forEach((g, i) => {
      const suffix = globs.length > 1 ? `-${i + 1}` : "";
      const name = `${slug}${suffix}.md`;
      const dest = path.join(root, OUT_SCOPED_DIR, name);
      const content =
        (noBanner ? "" : BANNER) +
        `<!-- applyTo: ${g} -->\n` +
        header +
        (parsed.content.trim() || "(empty rule body)") +
        "\n";
      scopedWrites.push({ dest, content });
    });
  }

  let alwaysBlock = "";
  if (alwaysParts.length > 0) {
    const inner =
      (noBanner ? "" : BANNER) +
      "# Project instructions (from Cursor rules)\n\n" +
      alwaysParts.map((p) => `## ${p.source}\n\n${p.body.trim()}\n`).join("\n");
    alwaysBlock = `${ALWAYS_BEGIN}\n${inner.trim()}\n${ALWAYS_END}\n`;
  }

  if (!dryRun) {
    const outScoped = resolvePathUnderRoot(root, path.join(root, OUT_SCOPED_DIR));
    await fs.mkdir(pathToFileURL(outScoped), { recursive: true });

    for (const { dest, content } of scopedWrites) {
      const dir = resolvePathUnderRoot(root, path.dirname(dest));
      await fs.mkdir(pathToFileURL(dir), { recursive: true });
      const abs = resolvePathUnderRoot(root, dest);
      const slug = path.basename(abs, path.extname(abs));
      let prior = "";
      try {
        prior = await fs.readFile(pathToFileURL(abs), "utf8");
      } catch {
        /* new */
      }
      const merged = mergeScopedRuleFile(prior, slug, content);
      await safeWriteFile(root, dest, merged, "utf8");
    }

    const alwaysPath = path.join(root, OUT_ALWAYS);
    let prior = "";
    try {
      const alwaysFile = resolvePathUnderRoot(root, alwaysPath);
      prior = await fs.readFile(pathToFileURL(alwaysFile), "utf8");
    } catch {
      /* new */
    }

    let next = prior;
    if (prior.includes(ALWAYS_BEGIN) && prior.includes(ALWAYS_END)) {
      const re = new RegExp(
        `${escapeRe(ALWAYS_BEGIN)}[\\s\\S]*?${escapeRe(ALWAYS_END)}\\n*`,
        "m"
      );
      next = prior.replace(re, "");
    }

    if (alwaysBlock) {
      const sep = next.trimEnd().length ? "\n\n" : "";
      next = `${next.trimEnd()}${sep}${alwaysBlock}`;
      await safeWriteFile(
        root,
        alwaysPath,
        next.endsWith("\n") ? next : `${next}\n`,
        "utf8"
      );
    } else if (next.trim().length > 0) {
      await safeWriteFile(
        root,
        alwaysPath,
        next.endsWith("\n") ? next : `${next}\n`,
        "utf8"
      );
    }
  }

  return {
    ok: true,
    message: `Processed ${ruleFiles.length} rule file(s).`,
    alwaysParts,
    scopedWrites,
    alwaysPath: alwaysBlock ? path.join(root, OUT_ALWAYS) : null,
    dryRun,
  };
}

module.exports = {
  convert,
  walkFiles,
  assertPathInsideRoot,
  resolvePathUnderRoot,
  DEFAULT_RULES_DIR,
  OUT_ALWAYS,
  OUT_SCOPED_DIR,
};
