package com.amitchorasiya.cloude.toolbox.intellij.hub

/**
 * Every `CloudeCodeToolBox.*` command id from the VS Code extension `package.json` plus hub-only ids
 * so `runCommand` from the JCEF hub always resolves to an action.
 */
object VsCodeHubCommandIds {

    val ALL: List<String> = listOf(
        "CloudeCodeToolBox.openInlineChatCursorStyle",
        "CloudeCodeToolBox.openWorkspaceMcp",
        "CloudeCodeToolBox.openUserMcp",
        "CloudeCodeToolBox.mcpListServers",
        "CloudeCodeToolBox.mcpBrowseRegistry",
        "CloudeCodeToolBox.mcpAddServer",
        "CloudeCodeToolBox.portCursorMcp",
        "CloudeCodeToolBox.manualPortCursorMcpWithoutNpx",
        "CloudeCodeToolBox.syncCursorRules",
        "CloudeCodeToolBox.cursorRulesToClaudeWithoutNpx",
        "CloudeCodeToolBox.initMemoryBank",
        "CloudeCodeToolBox.memoryBankWithoutNpx",
        "CloudeCodeToolBox.workspaceSetupWizard",
        "CloudeCodeToolBox.openClaudeCode",
        "CloudeCodeToolBox.toggleMcpDiscovery",
        "CloudeCodeToolBox.refreshMcpView",
        "CloudeCodeToolBox.refreshWorkspaceView",
        "CloudeCodeToolBox.openInstructionsPicker",
        "CloudeCodeToolBox.appendCursorrules",
        "CloudeCodeToolBox.mergeCopilotInstructionsIntoClaudeMd",
        "CloudeCodeToolBox.openClaudeUserSettingsJson",
        "CloudeCodeToolBox.migrateCopilotSkillsToAgents",
        "CloudeCodeToolBox.revealCopilotSkillFoldersWithoutNpx",
        "CloudeCodeToolBox.createCursorrulesTemplate",
        "CloudeCodeToolBox.openCursorClaudeReference",
        "CloudeCodeToolBox.openComposerHub",
        "CloudeCodeToolBox.openSessionNotepad",
        "CloudeCodeToolBox.copySessionNotepad",
        "CloudeCodeToolBox.openClaudeCodeAccountDocs",
        "CloudeCodeToolBox.openEnvSyncChecklist",
        "CloudeCodeToolBox.translateContextSelection",
        "CloudeCodeToolBox.buildContextPack",
        "CloudeCodeToolBox.runThinkingMachinePriming",
        "CloudeCodeToolBox.showMcpSkillsAwareness",
        "CloudeCodeToolBox.showIntelligenceReadiness",
        "CloudeCodeToolBox.openIntelligenceSettings",
        "CloudeCodeToolBox.openThinkingMachineModeSettings",
        "CloudeCodeToolBox.openIntelligenceToolboxRepos",
        "CloudeCodeToolBox.openIntelligenceRepoMcpPort",
        "CloudeCodeToolBox.openIntelligenceRepoMemoryBank",
        "CloudeCodeToolBox.openIntelligenceRepoRulesConverter",
        "CloudeCodeToolBox.migrateSkillsCursorToAgents",
        "CloudeCodeToolBox.revealSkillFoldersWithoutNpx",
        "CloudeCodeToolBox.claudeToolboxConfigScan",
        "CloudeCodeToolBox.appendNotepadToMemoryBank",
        "CloudeCodeToolBox.createSkillStub",
        "CloudeCodeToolBox.verificationChecklist",
        "CloudeCodeToolBox.applyBundledMcpRecipe",
        "CloudeCodeToolBox.runFirstWorkspaceTestTask",
        "CloudeCodeToolBox.runOneClickSetup",
        "CloudeCodeToolBox.openOneClickSetupSettings",
        "CloudeCodeToolBox.openClaudeCodePanel",
        "CloudeCodeToolBox.openKitTarget",
    )
}
