/**
 * Pure formatting for context packs (unit-tested, no vscode imports).
 */

export const DEFAULT_PACK_NOTICE =
  "> **Review before sending to Claude Code** — pasted `#file:` lines are hints only; remove anything sensitive.\n\n";

export type ContextPackParts = {
  /** Shown at top (privacy / attachment caveat) */
  notice: string;
  workspaceFolderName: string;
  workspaceRootPath: string;
  activeFile?: {
    relativePath: string;
    languageId: string;
    selection?: string;
  };
  /** Relative paths, already de-duped; will be sliced in formatter */
  openEditorRelativePaths: string[];
  diagnosticsSection?: string;
  gitSection?: string;
  limits: {
    maxOpenEditors: number;
    maxSelectionChars: number;
  };
};

export function truncateText(s: string, maxChars: number): string {
  if (s.length <= maxChars) {
    return s;
  }
  return `${s.slice(0, maxChars)}\n\n… (${s.length - maxChars} more characters truncated)`;
}

export function buildContextPackMarkdown(parts: ContextPackParts): string {
  const { maxOpenEditors, maxSelectionChars } = parts.limits;
  const lines: string[] = [];
  lines.push(parts.notice.trimEnd());
  lines.push("");
  lines.push("## Workspace");
  lines.push(`- **${parts.workspaceFolderName}**`);
  lines.push(`- Root: \`${parts.workspaceRootPath}\``);
  lines.push("");

  if (parts.activeFile) {
    lines.push("## Active editor");
    lines.push(`- Path: \`${parts.activeFile.relativePath}\``);
    lines.push(`- Language: \`${parts.activeFile.languageId}\``);
    if (parts.activeFile.selection?.trim()) {
      lines.push("- Selection:");
      lines.push("```text");
      lines.push(truncateText(parts.activeFile.selection, maxSelectionChars));
      lines.push("```");
    }
    lines.push("");
  }

  const editors = parts.openEditorRelativePaths.slice(0, maxOpenEditors);
  lines.push("## Open tabs (recent / visible)");
  if (editors.length === 0) {
    lines.push("_No workspace-relative file tabs found._");
  } else {
    for (const p of editors) {
      lines.push(`- \`${p}\``);
    }
  }
  lines.push("");
  lines.push("## Suggested file references");
  lines.push(
    "_Use `@` file picks in Claude Code where possible. Lines below are paste hints (`#file:` style)._"
  );
  lines.push("");
  for (const p of editors) {
    lines.push(`#file:${p}`);
  }
  lines.push("");

  if (parts.diagnosticsSection?.trim()) {
    lines.push("## Diagnostics");
    lines.push(parts.diagnosticsSection.trimEnd());
    lines.push("");
  }

  if (parts.gitSection?.trim()) {
    lines.push("## Git");
    lines.push(parts.gitSection.trimEnd());
    lines.push("");
  }

  lines.push("---");
  lines.push("_Generated by Cloude Code ToolBox — Intelligence context pack._");
  return lines.join("\n");
}
